### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by timburks** [spiricom/LEAF#10]
Thanks for sharing! Would you be willing to put an open source license on this project? GitHub [makes it easy](https://help.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository) and if you don't have a preference, I think the MIT License might be easiest for people to generally use.

**Comment by spiricom** [comment]
Yup - I've been planning to clarify this. I just added an MIT license to it. I needed to anyway since there is some ported code from both the STK (sound tool kit) and the Puredata source code, which both have basically that MIT license.
